json: added custom marsheler
roytman/ovsdb-etcd pull request #2
Opened 2021-02-15 14:18 UTC by hunchback

still work-in-progress

2021-02-17 20:03 UTC, roytman requested changes

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode.go
> +type NB_Global struct {
NB_Global is not part of the encoder

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode.go
> +}
Please add additional type - <named-uuid>
      
> A 2-element JSON array that represents the UUID of a row inserted
>       in an "insert" operation within the same transaction.  The first
>       element of the array must be the string "named-uuid", and the
>       second element should be the <id> specified as the "uuid-name" for
>       an "insert" operation within the same transaction.  For example,
>       if an "insert" operation within this transaction specifies a
>       "uuid-name" of "myrow", the following <named-uuid> represents the
>       UUID created by that operation:
> 
>       ["named-uuid", "myrow"]

https://tools.ietf.org/html/rfc7047#section-5

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode.go
> +type Set []string
in addition to strings, Set can contain other types,

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode_test.go
> +func TestUuid(t *testing.T) {
For this kind of tests, Ginkgo `Table Driven Tests` are more suitable

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode_test.go
> +func TestOptionsLength(t *testing.T) {
You don't have unit test for Set
The Set parsing is wrong, it should be `["set",["clustered","standalone"]]`, we have  `["set",[["clustered"],["standalone"]]]`

2021-02-17 20:03 UTC, roytman commented on pkg/json/encode_test.go
> +	fmt.Printf("expected: %s\n", expectedOptions)
pls remove the `Printfs`

2021-02-18 15:01 UTC, hunchback commented on pkg/json/encode_test.go
> +func TestUuid(t *testing.T) {
I know Ginkgo, but this is more a matter to taste .. and I am not crazy about that style of testing

2021-02-18 15:07 UTC, hunchback commented on pkg/json/encode_test.go
> +func TestOptionsLength(t *testing.T) {
ok

2021-02-18 15:09 UTC, hunchback commented on pkg/json/encode_test.go
> +	fmt.Printf("expected: %s\n", expectedOptions)
ok

2021-02-18 15:21 UTC, hunchback commented on pkg/json/encode.go
> +type Set []string
ok

2021-02-18 15:37 UTC, hunchback commented on pkg/json/encode.go
> +type NB_Global struct {
ok

2021-02-18 15:37 UTC, hunchback commented on pkg/json/encode.go
> +}
ok

2021-02-18 15:38 UTC, hunchback commented
@roytman - I addressed outstanding comments - please review

2021-02-18 15:41 UTC, roytman commented on pkg/json/encode_test.go
> +func TestUuid(t *testing.T) {
ovn-kubernetes uses Ginko, I prefer to be in-line with them, we will "sell" our code to this team

2021-02-18 19:08 UTC, roytman commented on pkg/json/encode.go
> +}
the first string should be "named-uuid"

2021-02-18 19:09 UTC, roytman commented on pkg/json/encode_test.go
> +func TestOptionsLength(t *testing.T) {
You did not fix  the set encoding

2021-02-18 20:27 UTC, hunchback commented on pkg/json/encode_test.go
> +func TestUuid(t *testing.T) {
ok

2021-02-18 20:28 UTC, hunchback commented on pkg/json/encode_test.go
> +func TestOptionsLength(t *testing.T) {
ahhh ... I see will do

2021-02-18 20:29 UTC, hunchback commented on pkg/json/encode.go
> +}
ok

2021-02-18 21:05 UTC, hunchback commented on pkg/json/encode_test.go
> +func TestUuid(t *testing.T) {
I will not have time to handle now, my preference is that this be delayed for later and that the PR is merged without handling this

2021-02-18 21:14 UTC, merged