adding ginkgo and gomega table driven test
roytman/ovsdb-etcd pull request #3
Opened 2021-02-21 12:33 UTC by OmerBenHayun

2021-02-21 12:41 UTC, roytman requested changes

2021-02-21 12:41 UTC, roytman commented on pkg/json/json_suite_test.go
> +		`"connections":["uuid","71a565df-188f-42d0-9f18-74e180e27889"],` +
connections should be type of set, please add an additional entry

2021-02-22 11:31 UTC, hunchback commented
would like to add my input that ginkgo test style has many disadvantages, and thus is not used in many leading project ... it in fact brings to very large functions making things less maintainable. I would suggest we refrain from going ahead with this change ... i can supply examples if needed

2021-02-22 12:36 UTC, roytman commented
Hi @hunchback , please provide this input about gingo/gomega. Maybe not in this PR, but as a separate file/note.

2021-05-16 06:56 UTC, hunchback commented
closing (can be reopened if becomes relevant)

2021-05-16 06:56 UTC, closed without merging